### ISSUE TITLE
PrepareAnnotationsFromGTF() not installed

### ISSUE THREAD

**Issue by qhauck16** [GoekeLab/bambu#154]
Hi, 
I'm attempting to use this software with a GTF as a reference annotation file for RNA-seq quantification. I noticed a recent commit message referenced the above function not being exported, and, as far as I can tell, it is still not working/appearing. I can use the prepareAnnotations() function fine. 

Thanks!
 
Quinn

**Comment by cying111** [comment]
hi @qhauck16 , thanks for the feedback! Yes, we have combined the two annotation functions to one function **prepareAnnotations**, so that you can use **prepareAnnotations** to prepare both gtf file and txdb object now. The **prepareAnnotationFromGTF** function now becomes an internal function, which will be called internally when gtf file is provided to **prepareAnnotations** function.
