### ISSUE TITLE
warnings when using multiple bam files

### ISSUE THREAD

**Issue by mei-du** [GoekeLab/bambu#206]
Hi team,
I have tried bambu with both BamFileLists and single merged bam files, and noticed a significant difference in runtime. I also received warnings only when using BamFileLists. Could you offer any clarification for this? Thank you!

![image (1)](https://user-images.githubusercontent.com/58542302/116504282-4b637900-a8fb-11eb-8525-f5d467ffb489.png)

**Comment by cying111** [comment]
Hi @mei-du , for the warnings, my guess would be of the bam files that you have, those that are rather small, with not much informative reads would throw this warning. It would not affect processing other bam files, so I would not worry about this too much! 

As for your first query to the big running time difference in using BamFileLists vs merged bam file, could you provide more details so that I can assess? 
- BamFileListd: range of file size, number of files
- merged bam file: file size

Thank you

**Comment by mei-du** [comment]
Hi @cying111,
BamFileList: 6 files, 20.6MB - 35.4MB
merged bam: 196.1MB

Thanks!

**Comment by cying111** [comment]
Thanks @mei-du ! All the bam files seem a bit small, I would probably expect quite few reads in these files which will cause the warnings. As for the running time, I probably would not expect much difference, may I know what is the running time when you run as BamFileLists vs Merged bam?

**Comment by mei-du** [comment]
Hi @cying111 it took about 11 minutes for BamFileLists and 5 minutes for the merged.

**Comment by cying111** [comment]
Did you use parallel computation when using BamFileLists? If not, then maybe using BamFileLists would cost a bit longer than the merged case because samples will be processed sequentially instead of parallelly.

**Comment by mei-du** [comment]
Hi @cying111,
No I didn't. I had suspected that, makes sense. Thanks for the clarification!
