### ISSUE TITLE
guidance on memory and multithreading

### ISSUE THREAD

**Issue by jackhump** [GoekeLab/bambu#208]
Hi, I'm excited to try out bambu. I'm currently working on a dataset which consists of 30 PacBio sequel II runs, which come to 88 million FLNC reads in total. I've been struggling to find a tool that can generate a single merged transcript reference and a count matrix for all samples together, which I could then perform downstream filtering and analysis with SQANTI and SWAN.

I'm currently getting to grips with bambu by using a couple of the smaller files but I would like to eventually scale up to the full dataset.  Would you be able to advise on the kinds of resources I would need to request to process the dataset with bambu within a reasonable time frame (< 7 days). 
For comparison, TALON and isoquant ended up using up to 135 GB of memory with 8-16 cores, taking between 4 and 6 days.

Thanks in advance!

**Comment by cying111** [comment]
Hi @jackhump , glad to hear that you are trying out our package. For the number of samples that you give, I would suggest you to run bambu with a memory of 124GB and 10 cores, it should be able to allow you to process the dataset within the requested time frame.

**Comment by jackhump** [comment]
I have a few specific questions now I'm looking more through the results:

1) The values in the transcript count matrix, how are these calculated? As they are decimals rather than integers, can I assume these are ML estimates? Or are these normalised like TPMs?
2) I ran the GTF through SQANTI and it classifies almost no transcript as ISM (incomplete splice match) - why is that? 
3) Looking at specific genes I'm noticing very few intron retention transcripts present, compared to earlier GTFs I assembled with Cupcake and TALON. Does bambu treat intron retention transcripts in a particular way?

**Comment by cying111** [comment]
Hi @jackhump , it's great to hear that you have managed to run bambu on your samples. For you specific questions, here are some quick answers:
1. count estimates are more than counts, we have used EM algotithm to do some estimation, so the count values reported are EM estimates.
2. I am quite happy that you bring this point up, in the bambu parameters, opt.discovery, there is a remove.subsetTx, which is used to indicate whether subset transcripts will be removed, i.e., incomplete splice match cases, by default, this parameter is set to TRUE. if needed, you can always set this parameter to FALSE.

We are preparing a manuscript for this, you can share with us your email address so that we can alert you when our preprint is out. Do let us know if you have further questions and feel free to reach to us through emails.
