### ISSUE TITLE
Mapping long reads from PCR to isofroms (novel and existing)

### ISSUE THREAD

**Issue by wigge206** [GoekeLab/bambu#230]
Hello, 
I have been working on mapping some targeted nanopore cDNA sequencing. We have generated reads for a one gene with two primer sets, one set are in the 5` and 3` UTRs and effectively capture the full-length products (slightly truncated). The seconds set are in a known second TSS start site which is in one of FL exon. 

I have used FLAIR and stringtie2, which seems to have handle the FL products well but are not doing well at the shorter isofroms. I had a quick play with bambu and there seems to be issue with non-full length isoforms (which all PCR product are). All the reads are being counted to novel transcripts. 
Are the options that can remedy this? Any suggestions?

**Comment by wigge206** [comment]
I have quickly run one sample through your pipeline using those setting. The sample only has reads from the shorter PCR isoform but is replicating the issue. 

The snapshot of the gtf is below, all the reads are mapped to novel transcripts (tx1, tx2, tx3), we would expect the reads to map to ENST00000610623.4 etc

![image](https://user-images.githubusercontent.com/7672246/138208463-6274f79b-547b-446e-9eba-3fee6399af68.png)

I would be happy to securely share some files if that makes troubleshooting easier.

**Comment by andredsim** [comment]
I see, it looks like the 3 novel transcripts all have intron retention events and a novel exon in tx.3. Do the other ENST transcripts receive 0 values for assays(se)$counts /CPM/fullLengthCounts/partialLengthCounts and unique counts?

If you could send me the .bam file for the reads in this area as well as the genome and annotation file I will try and run it myself to see if I can replicate or understand what is causing the issue. Also if you could send me the output se object from your run of Bambu as a .rds so I can compare my results to yours. 

Let me know which method of file transfer you would prefer.

**Comment by wigge206** [comment]
Hi, 

I have used the latest master branch version (and tried through the updated bioconductor release), and still are only have readCounts for novel transcripts. I used `rowData()` to inspect the results. `SessionInfo()` did confirm I was using version 2.0.0

I also used the `opt.discovery()` settings you suggested `opt.discovery = list(max.txNDR = 0.5, fitReadClassModel = FALSE)`
What settings did you use?

**Comment by andredsim** [comment]
Hi,

Instead of looking at rowData(se)$readCount could you please try assays(se)$counts, assays(se)$CPM, or assays(se)$fullLengthCounts and tell me what you get.

**Comment by wigge206** [comment]
Hi, 

For each of them I get a long list with the vast majority of entries as 0. Screenshot attached of the table summary for counts

![Screenshot 2021-11-05 150814](https://user-images.githubusercontent.com/7672246/140446473-9de67e0c-7b4d-4b09-bff8-25eaaeaee8c6.png)

I have attached the .rds for the bambu output.
[bambu_sample1.zip](https://github.com/GoekeLab/bambu/files/7480006/bambu_sample1.zip)
.

**Comment by andredsim** [comment]
Hi, 

Thanks for sending the rds, that helped me understand it better!

I did some tests and these are the parameters I ran with.
se <- bambu(reads = sample, annotations = annotations, genome = fa.file, verbose = T, rcOutDir = "./", opt.discovery = list(max.txNDR = 0.5, remove.subsetTx = FALSE, min.readFractionByGene = 0))
![image](https://user-images.githubusercontent.com/17838991/140448649-ad4ff55c-e77c-4100-8187-5365f08b904e.png)

Here is the rds file for this run incase it appears different for you.
[bambu_sample1_v2.zip](https://github.com/GoekeLab/bambu/files/7480091/bambu_sample1_v2.zip)

remove.subsetTx = FALSE means that any transcripts which are considered subsets (incomplete splice matches) of larger transcripts will still be included in the output. (These are removed by default as they often can just be degradation products)

min.readFractionByGene = 0 lowers the threshold required for a novel transcript to be expressed compared to other transcripts in that gene from 5% down to 0%. I think this is the big difference as one of the transcripts seems to be much more highly abundant than the rest which would cause the others to be precluded from the analysis because of this filter.

The reason there are lots of 0's in the quantification is because Bambu includes the quantification of all the transcripts included in the annotations. If I understand correctly as you have a sample where only a few genes are sequenced, the expected output would be that the majority are 0 since there are no reads for them.

Let me know if this makes sense and works for you!
