### ISSUE TITLE
BiocParallel Error: cannot mix "*" with other strand values

### ISSUE THREAD

**Issue by SheridanCavalier** [GoekeLab/bambu#231]
Hello!
I have been running bambu successfully with the mouse mm39 reference genome and the accompanying annotation file from UCSC; however, very recently this BiocParallel issue arises whenever I run the bambu function. During the "Start generating read class files" step of bambu, I receive this error "BiocParallel Error: cannot mix * with other strand values". 
When looking through my GRanges object, there are no annotations with * as the strand notation, and even if there were I feel that -, +, and * are normal strand notations. I understand that bambu denotes novel transcripts for which there are no canonical TSSs with "*" as the strand symbol because it was working a couple of days ago! Any help is much appreciated, I'm not sure if bambu or BiocParallel was updated within the last few days and I have tried all I can think of to fix this problem. Thank you for your time!

**Comment by andredsim** [comment]
Hi @SheridanCavalier, did updating the version as per cying111's comment resolve your issue so that we can close this issue?

If this didn't and your data isn't stranded so you don't want to use the stranded=TRUE solution here are two alternative solutions that might solve your issue. 

- If you are using a BSgenome, instead try using a fasta genome instead
- Try the BETA bambu branch "fix_bsgenome_strand_bug" which hopefully should stop the crash you mentioned

Hope this helps and please let us know if your problem is solved.

**Comment by SheridanCavalier** [comment]
@andredsim @cying111 
Yes! Sorry for the late reply, but the update fixes the issue thank you so much
