### ISSUE TITLE
quantification issue

### ISSUE THREAD

**Issue by JintaoL666** [GoekeLab/bambu#234]
library(ExperimentHub)
NanoporeData <- query(ExperimentHub(), c("NanoporeRNA", "GRCh38", "BAM"))
bamFiles <- Rsamtools::BamFileList(NanoporeData[["EH3808"]], NanoporeData[["EH3809"]],
    NanoporeData[["EH3810"]], NanoporeData[["EH3811"]], NanoporeData[["EH3812"]],
    NanoporeData[["EH3813"]])
Questions1:
Please explain the above script and the NanopreData?

Question2:
How could we load more than one bam files for quantification and differential expression analysis? 
Thanks a lot!

**Comment by cying111** [comment]
Hi @JintaoL666 ,

Thank you for using our tool! Please see my answer below:
Q1: We are using datasets from the NanoporeRNASeq package where we have generated 6 nanopore RNA-Seq samples that can be used to test out bambu. The bam files of these samples are uploaded to the hub instead of having it at local, the scripts are just how you can extract the datasets through the ExperimentHub package. `NanoporeData` is just a ExperimentHub object that contains the chain files of the bam files with specific ids created automatically for each sample, so these need to be correct in order to use them. You can check `NanoporeData` and `bamFiles` by typing the object name in R, like below:
`NanoporeData`
`bamFiles`
If you want to know a bit more about extracting data using ExperimentHub package, you can refer [here ](https://www.bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html )for the details: 

Q2: I am not sure I understand you correctly, but if you refer to how to use bambu to quantify more than 1 bam file, you can just simply provide paths of the bam files to be quantified as a vector of strings and supply it to the reads argument, as how we have done in the following steps of the scripts that you shared above in the vignettes.

Hope I have clarified your questions!
