### ISSUE TITLE
count normalization in counts_transcript.txt

### ISSUE THREAD

**Issue by imilenkovic** [GoekeLab/bambu#235]
Hello,

I was wondering what kind of normalization is used to produce the counts in the `counts_transcript.txt` file that is written with the `writeBambuOutput` command? I see that they are all decimal so I wonder if they are normalized by million reads or another way?

Thank you!

**Comment by cying111** [comment]
hI @imilenkovic , the reported counts in counts_transcript.txt is the estimated total read count for each transcript, there is no normalization involved. We used EM for probabilistic assignment of reads to transcripts, and that's why the estimates are not integers, but with decimals. Hope this clarified your question. Let us know if you have further questions. Thanks!

**Comment by bernardo-heberle** [comment]
Hi,

If a read of length 200bp maps uniquely to a transcript of length 800bp, will Bambu count that as 0.25 reads or 1 read?

Thank you,
Bernardo
