### ISSUE TITLE
BiocParallel errors: long vectors not supported yet

### ISSUE THREAD

**Issue by ChangqingW** [GoekeLab/bambu#244]
I got this error from running on mouse ONT reads. Seems like it is because the number of reads exceeding the limit for `BiocParallel::bplapply`?
```
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error: long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
In addition: Warning message:
In seqlevelCheckReadsAnnotation(readGrgList, annotations) :
  no annotations with matching seqlevel styles,
        all missing chromosomes will use de-novo annotations
```
My script:
```
options(error = quote(dump.frames("r.dump", TRUE)))
library("bambu")
bam<-"align2genome.bam"
fa.file<-'Index/GRCm38.primary_assembly.genome.fa'
gtf.file <-'Index/gencode.vM24.annotation.gff3'
bambuAnnotations <- prepareAnnotations(gtf.file)
se <- bambu(reads = bam, annotations = bambuAnnotations, genome = fa.file, quant = FALSE)
```
[r.dump.rda.zip](https://github.com/GoekeLab/bambu/files/8210516/r.dump.rda.zip)

**Comment by andredsim** [comment]
Hi,

Thank you for sending the r.dump file along with the issue. 

Unfortunately I wasn't able to investigate your bam and genome files because they are loading in after the bplapply and are not saved in the r.dump. However I did notice that the annotations file you are using has a length 0, meaning there are no annotations in it. This is what causes this warning message
```
"In seqlevelCheckReadsAnnotation(readGrgList, annotations) :
  no annotations with matching seqlevel styles,
        all missing chromosomes will use de-novo annotations"
```
So the sample was being run (I believe unintentionally) in _de novo_ mode which might cause the error you encountered.

I downloaded the annotation file you use and it looks like prepareAnnotations() isn't working with the gff3 file, however I also downloaded the .gtf file and  prepareAnnotations did work.

Could I please get you to try rerunning your sample with the .gtf file for now (accessible from https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/gencode.vM28.annotation.gtf.gz). If this works please let me know and in the mean time I will look into why bambu isn't working with the .gff3 format

If this doesn't work could you send please send me the bam file you are using (or a fraction of it if its too large and still causes the issue), so that I can troubleshoot further

**Comment by ChangqingW** [comment]
Thank you for your prompt response, it was indeed because of the gff3 annotation I used by mistake.
