### ISSUE TITLE
"Novel" highly expressed mitochondrial transcript discovered with Bambu not found in IGV genome browser read stack.

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#303]
Hi,

I am running human brain nanopore cDNA samples and doing quantification/discovery using Bambu. I recently found this novel highly expressed (~10^6 counts per sample) mitochondrial RNA species. This species had a spliced out intron as can be seen in the isoform at the top of the image:

 ![image](https://user-images.githubusercontent.com/81333350/183984539-b9427eb4-48d6-4541-8445-899635226d27.png). 

I was a bit skeptical since that is not usual for human mitochondrial transcripts so I took a look at the reads for this region on the IGV genome browser and did not find any reads supporting this spliced isoform. Here is the IGV stack plot for the region where the novel transcript should be located: [igv_stack_plot_video](https://drive.google.com/file/d/1G3OF8HxA2aIrS6Oo887A-HuU2R1leDCk/view?usp=sharing). The blue lines indicate where the spliced out intron should be located.

I looked at a few other non-mitochondrial novel transcripts found in our data and they all had corresponding reads on IGV genome browser. Normally I would just dismiss this mitochondrial transcript as a false positive and move on, but since it is one of the most highly expressed transcripts in our 4 samples I figured it was a good idea to report it and see if there is something special about the mitochondrial RNA that could be causing Bambu to make an error.

Here is the data/info needed to reproduce this:

- Bambu RDS Files (.zip): https://drive.google.com/file/d/1Lq0FbRjB_C2R8U2IqVixoUCLE2Ho5lU2/view?usp=sharing
- Counts and annotation from Bambu:  https://drive.google.com/file/d/1CW3yHxXZSlapdmPAdZ1YvXm9xgrDGnF1/view?usp=sharing
- Reference Genome (.fa): https://drive.google.com/file/d/1bIcVcndKTJUsG1IXQcJYdriLN03d5XFz/view?usp=sharing
- Reference Genome Index (.fa.fai): https://drive.google.com/file/d/1N2G8zghpwtE-3OEMxwvSoI1yp1BpD8pJ/view?usp=sharing
- Reference Annotation (.gtf): https://drive.google.com/file/d/14Sl0yhZZSakRmbHVDW7-XYlZoRw--J9x/view?usp=sharing
- Singularity Image (Bambu version 2.2.0): https://drive.google.com/file/d/1PQ7ciwbMdWR7tm1VHlVO0ZlgIT4JY4If/view?usp=sharing
- R script used to run Bambu: https://drive.google.com/file/d/1z2-pJLtdtWS2zW4vH5WMNNTjYNIHF8jc/view?usp=sharing

The mitochondrial transcript in question can be found in the extended annotations and counts files with name "tx.755".

Thank you for your time and for the great work developing this tool!

**Comment by andredsim** [comment]
Hi,

Thanks for leaving such a detailed bug report and I apologize for the delayed reply. I have gone through your RDS files and could mostly replicate your observation. It seems there is a 2 prong error.
 1. I find several spliced transcripts reported by Bambu in this area, which does not match the IGV video you uploaded (a discovery error). From the final bambu output I would expect 1475 reads that have this splice junction. 
 2. The read count that are present for these transcripts shouldn't be translating into such high counts that are seen in the counts_transcript.txt (a quantification error). This maybe due to the high number of fragments overlapping with this "transcript" seen in the IGV track. 
 
I noticed that the number of reads (reported by Bambu) found aligned to the MT chromosome ranged from 25-38% across the four samples. Do you expect this in your data? If not does samtools idxstats on your bam file return similar numbers? The Nanopore samples we typically work with have significantly less (which might also be why we didn't pick up on this earlier if it is a MT specific issue). 
 
Would it be possible to share one of the bam files with me (or at least a truncated version of the bam file with just the mitochondrial reads in it) so that I can rerun bambu and track the read ids for this spliced transcript to find out exactly where these transcripts are coming from? We discard individual read information before we create the .rds (for memory reasons) so I can't recover it from the .rds alone unfortunately. 

Finally just as a sanity check, I notice in the IGV browser, the MT chromosome (as named in the annotation file you sent me) is called chrM and the genome you have selected is named differently from the file you sent me. Is the genome file you used in the IGV browser, what you used to generate the .rds files, and the second run of bambu all the same?

**Comment by bernardo-heberle** [comment]
Hi @andredsim,

No problem, thank you for the reply and for looking into this.

Yes, we do expect a high % of reads aligning to the MT chromosome. These samples are from human brain, which has high energetic needs and thus ends up having a much higher percentage of mitochondrial reads than most other tissues. I took a quick look at the samtools idxstats for the bam files and they return similar numbers.

Of course, no problem. Here are the [bam](https://drive.google.com/file/d/181DxeVyBzxZWv6kBOZABT14XSY3KZtYf/view?usp=sharing) and the [bai](https://drive.google.com/file/d/1JjObtAV14kHUFp9ahYC4rSKABliCuBgK/view?usp=sharing) files for one of the samples.

Yes, they are all hg38. For some reason the built-in IGV browser hg38 reference genome has a different name for the mitochondrial chromosome than the gtf file from ENSEMBL. Just to be sure I did a quick check using the same hg38 reference genome that I included on this issue. Everything looks the same as in the previous IGV stack video I sent.

**Comment by andredsim** [comment]
Hi,

Thanks for the bam file. I was able to find several reads (40) that matched this junction albeit not as high level as the counts table would indicate.
![image](https://user-images.githubusercontent.com/17838991/185052036-54430fcb-c56a-4c10-a9d0-ed462faa5af6.png)
As to why they can't be seen in IGV, and this took me awhile to realize, but because there are so many reads in this location, by default IGV down-samples them and as reads with these junctions are relativity rare, they are more likely to be sampled out. 
I tried to get an IGV image of the reads myself by turning off downsampling, but there were too many reads, I didn't have enough memory to find it!
![image](https://user-images.githubusercontent.com/17838991/185052949-e9b4bddf-2f4f-41bf-aafd-93d900d0ab53.png)

So that's the first problem explained, there are legitimate reads with these junctions (probably an alignment error rather than being biologically real). 

As to why this transcript is occurring in the extended annotations - the currently parameters you are running bambu with have the NDR at 0.7 which is very high (high meaning lots of sensitivity and low precision (approximately 30% precision!). This means as you suggested in the first post, this is likely a false positive. Additionally I believe because it has such high read counts being on the MT chromosome it is also weighted as more likely being a real transcript when compared to normal transcript models. Bambu was designed under the assumption all transcripts in the sample follow similar behaviors, however the MT transcripts would break this assumption (given their high expression, which would warp the training). I will have to do some thinking of how Bambu might detect and handle this in the future! 

In the meantime I would recommend/suggest the following:

1. use a lower and more precise NDR threshold
2. try running bambu without the MT chromosome reads (or if you are interested in the MT transcripts, only the MT reads, however there might not be enough annotations for this)
3. try running bambu using the pretrained model (without fitting) by setting opt.discovery = list(fitReadClassModel = FALSE). This means the non MT transcripts should be scored using a model that isn't biased by the high MT fraction. 

As to the second problem as to why the quantification make it look like this transcript is super highly expressed even though it only has 40 full length reads supporting it (in this 1 sample). Because this transcript passed the NDR threshold it was introduced into the annotations. Then because of all the many overlapping reads that we can see in IGV partially overlap with it, we need to consider them as being potentially sourced from this transcript, explaining the inflated counts. The only way to solve this is to use annotations that do not have this transcript in it, either via the suggestions above, or manually removing it before the quantification step.

I hope this helps. If you have further questions or if I didn't adequately explain what is happening feel free to comment again and I can reopen the issue.

**Comment by bernardo-heberle** [comment]
That's great, thank you for your thorough analysis of the bug! The suggestions you gave should do the trick. 

I actually meant to be more stringent/precise with the gene/transcript discovery, but I misinterpreted the documentation. I thought a higher NDR would yield more precise results, but it is actually the opposite. Now that I think about it a bit more that makes sense that a lower Novel Discovery Rate would yield more precise and less sensitive results. I will re-run the analysis with an NDR=0.3 and I imagine this issue should be resolved.

My only suggestion is to revise the current NDR documentation. The phrasing was a bit confusing for me, and other users could have a similar experience. Currently it looks like this:

![Screenshot 2022-08-17 095317](https://user-images.githubusercontent.com/81333350/185153095-baff4de7-665b-45f3-ad83-2be6b8ba009c.png)


I would recommend saying something along these lines: "Set novel transcript discovery rate to 50% of the detected transcripts. Lower NDR generates more precise and less sensitive results."

**Comment by andredsim** [comment]
Great, thanks for your suggestion, it is definitely very unclear there. We do have an updated documentation branch that is being rolled out with the next big update aptly named "documentation_update". You are welcome to read that, it won't be 100% accurate to the current version you have but the concepts should be the same. 

Best of luck!
