### ISSUE TITLE
BAMBU extended gtf file output? 

### ISSUE THREAD

**Issue by seongwoohan** [GoekeLab/bambu#315]
Hello there, I want to know what "extended_annotations.gtf is here (https://github.com/GoekeLab/sg-nex-data/blob/master/docs/SG-NEx_Bambu_tutorial.md#running-bambu)," one of BAMBU's main outputs. It sounds like extended_annotations.gtf is a file with the entire reference annotation plus all discovered novel transcripts. This is a size of about 200 Mb. What I am trying to get is something like "transcript_models.gtf" that has just constructed transcripts (both known and novel), so no entire reference annotation. To my knowledge, its size is 90 ~ 100 Mb. Is there a way to gain that filtered gtf through the command line?

I am using cDNA ONT and cDNA PacBio datasets. I am providing the command line I used to convert from .fastq file to bam file below for cDNA ONT in case I missed something.

```
./minimap2 -t 8 -ax splice /home/seong/R/x86_64-pc-linux-gnu-library/4.1/bambu/extdata/hg38.fa /data/long_read/ENCBS944CBA/ENCFF263YFG.fastq -o /data/long_read/ENCBS944CBA/ENCFF263YFG.sam

samtools view -@ 8 -Sb -o /data/long_read/ENCBS944CBA/ENCFF563QZR.bam /data/long_read/ENCBS944CBA/ENCFF563QZR.sam
```

One another question that I have is, does BAMBU detect intron retention? Let me know for these questions, thanks a lot!

**Comment by andredsim** [comment]
Hi there,

Did you try the code I posted in the other issue? This line filters the output and you can then write the output as usual.

`constructedAnnotations = se[assays(se)$fullLengthCounts > 0]`

If you only want the annotations that are novel and not found in the reference annotations:

`novelAnnotations = se[mcols(se)$newTxClass != "annotation"]`

Let me know if this doesn't work for you.

Bambu does detect intron retention transcripts (and I have been able to find several on our own data!), by default Bambu doesn't output single exon transcripts, so only intron retention events that still result in multi-exon transcripts will be in your run though. If you are solely running bambu to look for intron retention transcripts I would recommend a higher NDR threshold to increase your sensitivity. 

The manuscript is coming soon! Be on the look out for it.

Let me know if you have any more questions! :)

**Comment by seongwoohan** [comment]
Thank you for the kind explanation! I did try your suggestions. Let me draw an example that I want :)

Imagine this Venn diagram with genome reference and BAMBU.

What `novelAnnotations = se[mcols(se)$newTxClass != "annotation"]` does is finding the roman number II, which is transcripts (or junctions) only found in BAMBU, not in reference. This contains 288 kb. What I want is **roman number II + roman number III**. If I have the area intersection of reference and BAMBU, the size will increase up to 90 ish Mb. 

What "extended_annotations.gtf" is giving is roman number I + II + III. I am trying to get roman number II + III because I want to know how much BAMBU finds its own novel transcript and how much it intersects with reference to see the relationship between II and III.

Let me know if you can help me with this!

<img width="188" alt="Screen Shot 2022-09-15 at 9 59 54 AM" src="https://user-images.githubusercontent.com/19489536/190423713-2ae839fc-50af-430a-b3ef-a10c83d51bb7.png">

**Comment by seongwoohan** [comment]
I forgot to add the first command line results. I get this error for that one in the screenshot. Anyway, let me know about the roman number II + III, thank you!

<img width="680" alt="Screen Shot 2022-09-15 at 11 10 12 AM" src="https://user-images.githubusercontent.com/19489536/190440619-ca484e12-b150-4e47-846f-8425b220d7b1.png">

**Comment by andredsim** [comment]
Hi,

For the line you ran (constructedAnnotations = se[assays(se)$fullLengthCounts > 0]) that should filter down to II + III.
The red text is just a warning not an error. It leaves you with 26687 constructed transcript models.
To output this use
`writeBambuOutput(constructedAnnotations, path = "./YOUR_PATH_HERE/")`

I hope I understood you correctly and could solve your issue. I am going on leave for the next week so I won't be able to reply quickly. If this still doesn't work for you I will reply as soon as I get back.

**Comment by seongwoohan** [comment]
Thank you for the help! I got the output as I requested. I guess I need more time to play with BAMBU. Have a good vacation :)

**Comment by yangqimeng99** [comment]
Hi bambu team,

I found this issue because, like the original poster, I'm also working with cDNA long-read data from multiple platforms. My case is at a much larger scale, so I'd really appreciate your guidance on the recommended workflow.

In total I have 1000+ samples spread across three sequencing platforms: PacBio, ONT, and another nanopore-based long-read platform similar to ONT. My goal is to build a single, unified transcript annotation (one `extended_annotations.gtf`) from all of them, so that novel transcripts receive consistent IDs across the whole cohort.

My questions:
**Mixed-platform, single run:** Can I pass all of these samples — the per-sample BAMs (or precomputed rcFiles) from all three platforms — directly into one `bambu()` call (`reads = c(...)`) to produce a single combined discovery result? Or does bambu expect all inputs in one run to come from the same platform?
**Effect of mixing platforms:** The three platforms differ in error/read-length profiles and are aligned with different minimap2 settings — broadly, PacBio is a high-accuracy long read, while ONT and the third platform are nanopore-based. Does combining them in one run affect model training or NDR estimation? I understand bambu trains a model and scores novel transcripts per-sample by default — so is cross-platform mixing handled naturally, or would you instead recommend running discovery separately per platform (or per technology type) and then merging the annotations?
**Scaling to 1000+ samples:** What is the recommended workflow for discovery + quantification at this scale? Specifically:

Is the rcFile approach (generate rcFiles once per sample, then run discovery on all of them together) the intended path here?
Any guidance on `lowMemory`, `ncore`, and the expected memory/runtime at this scale?
Is there a practical upper limit on the number of samples for a single joint discovery run, or a point where you'd suggest a two-step strategy (per-batch or per-platform discovery → merge)?

The version I'm currently using: **bioconductor-bambu v3.12.1**

Thanks a lot for this great tool, and for any best-practice recommendations for a mixed-platform, large-cohort setup!
