### ISSUE TITLE
Plans for Single Cell Support

### ISSUE THREAD

**Issue by atrull314** [GoekeLab/bambu#338]
Hi,

I just had a question on whether there will be plans for this tool to support single cell data? I know that there's a way to produce the transcript-to-read mappings and build the count matrix ourselves, but because that takes the quantification piece out, I was just curious if there were any plans to integrate this within bambu so there would be an option to produce single cell barcode matrices?

Thanks for your help!

**Comment by andredsim** [comment]
Hi,

Thank you for your interest in Bambu. We do want to look at if we can adapt Bambu for singe cell data in the future, however there are no imminent plans to release this yet. 
Whilst this is not the most convenient method and is untested by us, have you tried splitting the bam file by cell and submitting them essentially as separate samples in a multi-sample analysis in Bambu. This should provide you a matrix at the end with CPM and other quantification measures for each cell. 
Because this method might impact transcript discovery, you could first do a run with the full sample and save the annotations to use in the multi-sample (cell seperated run) and set discovery = FALSE.
It would be great to hear from a user if this produces decent results for you and let me know if you need me to explain what I mean above in more detail.

**Comment by lianov** [comment]
@andredsim : thanks for the reply. I am working with @atrull314 in the development of the nf-core `scnanoseq` pipeline (see original proposal at <https://nfcore.slack.com/archives/CE6SDEDAA/p1660666891400089>

Indeed, when we discussed adding `bambu`, the most benefit we saw was to attempt to add the quantifications. Given there is no current support for this, our current plan is to implement `bambu` as the default caller for transcripts at the "Exon Feature Assignment" step we have in the workflow figure from the link above (which we will update to reflect updated tools in the near future). This will (at the moment) allows us to at least implement annotations with downstream quantification still happening with `umitools`.

That being said, I think the above plan will be our first pass - what you suggested has intrigued me and I can see that being a feasible step (with what we are currently working on being used as a way compare results at a high-level. and also have the annotations you mentioned).

Thus, I will be happy to look into this when we get to it and if we find anything useful, I will be sure to share here (or if someone else jumps ahead and tests the suggestion, we will be sure to add this on to `scnanoseq` at the time).

**Comment by jonathangoeke** [comment]
thanks, yes please share any update! It looks like Bambu for transcript discovery might be a great addition to the pipeline. I also joined the slack channel on nf-core

**Comment by lingminhao** [comment]
Hi @lianov , I am part of the bambu team, currently planning to expand bambu to adopt single cell data. We are interested in the `scananoseq` that you plan to build. Do you currently have any discussion groups for this plan? I would be interested to join and potentially provide some information about bambu if you need it while implementing it in your pipeline.

**Comment by lianov** [comment]
@lingminhao : That would be great and yes we have a `scnanoseq` channel in the nf-core slack group, the following should link you to it: <https://nfcore.slack.com/archives/C03TUE2K6NS>.

Looking forward to our discussions.
