### ISSUE TITLE
Questions regarding example in README.dm

### ISSUE THREAD

**Issue by piechottam** [GoekeLab/bambu#349]
In
[Example](https://github.com/GoekeLab/bambu#modulating-the-sensitivity-of-discovery-pre-and-post-analysis)

```R
newAnnotations <- bambu(reads = test.bam, annotations = annotations, genome = fa.file, NDR = 1, quant = FALSE)
annotations.filtered <- newAnnotations[(!is.na(mcols(newAnnotations)$NDR) & mcols(newAnnotations)$NDR<0.1) | is.na(mcols(newAnnotations)$NDR)]
se.NDR_1 <- bambu(reads = test.bam, annotations = annotations.filtered, genome = fa.file, NDR = 1, discovery = FALSE)
```
* The first line starts transcript discovery and retains everything.
* What does it mean if `is.na(mcols(newAnnotations)$NDR) == TRUE`? Are known transcripts marked with `NDR` = NA?

Can the example be shortend to:
```R
newAnnotations <- bambu(reads = test.bam, annotations = annotations, genome = fa.file, NDR = 1, quant = FALSE)
se.NDR_1 <- bambu(reads = test.bam, annotations = newAnnotations, genome = fa.file, NDR = 0.1, discovery = FALSE)
```
Why is separate filtering step needed?

Thank you for the tool!

**Comment by andredsim** [comment]
Hi,

This part of the tutorial is for the case where you would like run quantification at different NDR threshold levels without needing to run the read class and discovery steps multiple times.  If you only plan to run Bambu once, you could just run Bambu with one line, with the desired NDR, and discovery and quant = TRUE. In this case, the second line is there, as you correctly inferred because some known transcripts will be marked with an NDR of NA and we do not want to filter these out. Known transcripts, for which a full length read-class was detected will still be assigned an NDR. 

This separate filtering step is needed because NDR filtering only occurs during the discovery step and determines which transcripts end up in the annotations to be used for quantification. If you ran Bambu using the second example the NDR parameter of 0.1 would not be used, and every single putative transcript would be used in the quantification step, likely to the detriment of accurate isoform quantification.  

I hope this answers your questions, please let me know if you have another further questions.

Thanks for using Bambu.

**Comment by andredsim** [comment]
Hi,

Close, see the amended below.
NDR == NA -> known transcript but NOT observed in reads
NDR >= 0.0 -> (NEW transcript OR KNOWN transcript) AND observed in reads

For example if a known transcript has a higher NDR, it could mean this is an annotation that was observed in the reads but Bambu has low confidence it is a full-length transcript. This could simply mean there was less evidence for the transcript in this sample, or that the annotation could be incorrect.
