### ISSUE TITLE
Issue with `writeBambuOutput`

### ISSUE THREAD

**Issue by paulimer** [GoekeLab/bambu#353]
Hi all,
With the test code of the README, followed by the line
```r
writeBambuOutput(se, "path/to/out_dir")
```
produces the error 
```r
Error in `left_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
```
which seems to be produced by [this line](https://github.com/GoekeLab/bambu/blob/master/R/readWrite.R#L99). 
From what I've seen the `all = TRUE` argument is a valid `dplyr::left_join` argument. Perhaps it was the case in a previous dplyr version?
Thanks in advance!

**Comment by gabee-chan** [comment]
I'm also having this problem. :( Does anyone know a solution to get the writeBambuOutput() outputs?

**Comment by cying111** [comment]
Hi @paulimer @gabee-chan , thanks for pointing this problem out! It turns out this error was related to the update of package dplyr, there are two solutions to this:
1) either use the older version of dplyr
2) use the [bug fix branch](https://github.com/GoekeLab/bambu/tree/writeBambuOutput_patch) for now
 
while we are updating the release branch

Please do try out the solutions and let us know if the error persists

I will also come back again to this issue once we have updated the release branch

**Comment by cying111** [comment]
Hi here, the bug is now fixed in the release branch, I will close this issue now. Thank you!
