### ISSUE TITLE
Re-running quantification after filtering transcripts without unique or full-length support to improve quantification accuracy

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#362]
Hello,

I am planning on using Bambu for a large-scale human experiment (~300 samples - 1 PromethION flowcell per sample).

With that in mind, it seems reasonable to infer that if a transcript does not have either full-length or unique support from at least one of the 300 samples then it must not be expressed in the tissue of interest.

I was wondering if I could run Bambu with both discovery and quantification on these 300 samples and then filter the extended annotation to only include transcripts with full-length and/or unique read support. Then I could re-run the quantification step using this filtered extended annotation, which should provide more accurate quantification of transcripts.

Does this approach seem sound to you? Are there any caveats that I should consider when running this analysis?

Thank you for all your great work!

**Comment by andredsim** [comment]
Hi,

During quantification, bambu does try reduce the impact of unexpressed transcripts impacting the quantification of other transcripts, however because we cannot be certain it isn't present we still account for them. I think in your experimental set up I would agree that is would be extremely unlikely for a transcript not to be found in over 300 PromethION samples if it truly is expressed. Therefore in my humble opinion the approach seems sound (with the caveat we have not evaluated this ourselves). In our paper we found that full-length reads was better than unique read support for filtering out non-expressed transcripts.

Because this is likely to a large amount of data I would suggest you run all the samples first with discovery and quantification off  and rcOutDir set to an output directory to produce all the intermediate RC files. You do not need to do all 300 samples in one command, if memory is an issue.
Then once you do discovery and quantification you can provide all 300 rcFiles as input to reads in one command. 
This also means when you rerun quantification the second time you can reuse these rcFiles, saving a lot of time.

We also have found an area in bambu that is quite slow in the discovery step when running with a large number of samples (>100) and have found a working solution but it is not yet part of the master branch as we still need to evaluate it. I would recommend just checking back with us once you have the data to see if we have merged this change into the master branch or if we have a development branch we suggest you to use.

I hope this helps, and let us know how this goes.

**Comment by bernardo-heberle** [comment]
Thank you for the very helpful response @andredsim,

We are going to start sequencing this larger cohort sometime in the second half of the year, so there is plenty of time before we have a large number of samples (>100). I will definitely check back with you all once I have the data.
