### ISSUE TITLE
Performing transcript discovery for multiple tissue types wiith Bambu

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#369]
Hello,

I am currently starting to run Nanopore long-read RNAseq data from multiple human tissues through Bambu. I was wondering if you have any recommendations on how to go about transcript discovery when multiple tissues are involved? We have 6+ samples for each tissue and I was wondering about the possible advantages and drawbacks of performing transcript discovery on all tissues at once versus performing transcript discovery for each tissue type separately?

I imagine there might be some important differences between the two approaches, but I don't know enough about the model behind Bambu to be able to infer what these differences might be.

Any help is much appreciated!

**Comment by andredsim** [comment]
Hi, 

You are correct that there are advantages and disadvantages for each method, however it is important to note that bambu will train a model on each sample separately so the intermediate rcFiles (.rds output) are unchanged regardless on if you run the samples together or separately. Therefore as long as you keep these files you can try discovery and quantification together and seperately much quicker

If you run all tissue samples together Bambu will pool all transcripts that rank highly together (by default it needs to be ranked highly in 1 in only one sample but this can be changed with the opt.discovery min.sampleNumber parameter). Then it will use all these discovered transcripts in quantification. This is advantageous because it means you get abundance estimates for all novel transcripts across all samples, which makes differential analysis easier. This can introduce a bias however if the novel transcripts found in one sample are not found in others, as it can "steal" reads from similar transcripts because of possible ambiguous assignment, in the same way non-expressed reference annotations do. 

If you do discovery and quantification using each tissue individually you are more likely to get more accurate quantification estimates for both the novel transcripts and reference transcripts in that tissue, However you will only be able to easily compare the reference transcripts between tissues and the novel transcript ids for each tissue will be arbitrary. 

If yout focus is only transcript discovery and you are not worried about tissue specificity of the discovered transcripts then I would generally recommend running all the tissues together. I will caution, from my experience, that with the default min.sampleNumber of 1, if you include a sample which is an outlier (significantly more or less reads than other samples, or sequenced with a different platform) it may unduly impact the precision of the output because the model trained on that sample is likely to be very different.

I hope this helps, and let me know if you have any further questions.

**Comment by bernardo-heberle** [comment]
This was very helpful, now it will be much easier to understand the impact of the decision in the analysis.

Thank you!
