### ISSUE TITLE
question:features used for junction correction.

### ISSUE THREAD

**Issue by HongYhong** [GoekeLab/bambu#381]
Hi Bambu team,
I'm studying the Bambu code and I have a question. My understanding of the junction correction part is that Bambu uses features such as the number of supporting reads for the splice site itself, the number of supporting reads for adjacent splice sites, the ratio and distance between them, as well as strand information. I'm not sure if my understanding is correct. Also, I haven't seen any information about the use of splice motifs. Did I miss something in the code, or are these indeed the only features used? Thank you for your response.
https://github.com/GoekeLab/bambu/blob/ffa53178915bc4f939f80f489a511f1b1861a27c/R/bambu-processReads_utilityJunctionErrorCorrection.R#L85C1-L87C76

**Comment by andredsim** [comment]
Hi, Sorry for the late response here.

You are correct about the features used for the calculation of the splice site prediction score. 
Bambu does use the splice motifs in order to help strand the junctions and read classs. 
You can look at spliceStrand() in bambu-processReads_utilityCreateJunctionTables.R.
This considers the following as the possible strand motifs `"GT-AG" "GC-AG" "AT-AC" "AT-AA" "AT-AG"`

I hope this helps and let us know if there are any further questions.

Kind Regards,
Andre Sim

**Comment by HongYhong** [comment]
@andredsim Got it! thank you for your helpful response!
