### ISSUE TITLE
Question: Could there be any difference in the output when the "lowMemory" is set to True in bambu?

### ISSUE THREAD

**Issue by youyupei** [GoekeLab/bambu#382]
Hi bambu developers,

I am developing an analysis pipeline and trying to use Bambu for isoform identification as one of the steps. I just noticed that there is a `lowMemory` option and it seems Bambu uses less memory and also runs faster with this `lowMemory=True`. Given that it's not the default option,  I was wondering whether there is any disadvantage to setting `lowMemory=True`? 

Thanks in advance.
Yupei

**Comment by andredsim** [comment]
Hi Yupei,

There should be no difference in output when lowMemory is True. When set to true it does read class construction by chromosome instead of all together, which reduces the maximum memory burden. Theoretically this should be slower for organisms that have a lot of chromosomes, however it is not necessarily the case. If you test it on your samples and you find it runs faster than I do not see a disadvantage from my perspective.

Kind Regards,
Andre Sim

**Comment by youyupei** [comment]
Hi Andre,

Thanks very much, and it makes a lot of sense.

Regards,
Yupei
