### ISSUE TITLE
Subsetting annotation for protein_coding biotypes

### ISSUE THREAD

**Issue by kenneditodd** [GoekeLab/bambu#387]
I want to subset my data to only look at protein_coding biotypes. I was originally just going to subset my bambu transcript quant output files. However, I then wondered if it would be better to subset the original gtf file before running prepareAnnotations() as the counts may be assigned differently. Which do you recommend?

**Comment by cying111** [comment]
Hi 

I think that is largely depending on your dataset. If you expect some level of expression in non-protein coding genes, it's better do the filtering afterwards as pre-filtering would affect both transcript discovery and quantification. Otherwise, you can do it before running prepareAnnotations and bambu.

Hope this clarifies your question!
Thank you
Ying

**Comment by kenneditodd** [comment]
@cying111 Thank you!
