### ISSUE TITLE
Use with prokaryotes to ID operons(?)

### ISSUE THREAD

**Issue by kneubehl** [GoekeLab/bambu#431]
Hi there,
This is a question not an issue. I was wondering if it possible that bambu could be used to ID operons in bacterial long-read cDNA sequencing. Conceptually, to me at least, an operon and exon usage could be similar at a gross scale. Retention of certain genes in an operon in similar genomic space could be like exon retention though the length of "introns" (i.e. intergenic space) would likely be a lot smaller and there would be no defined splice junctions. I am wondering if using the single exon settings might help to flush out the operons which could then be used to help better quantify gene expression. Compared to short-read RNAseq quantification tools I am worried about multi-mapping issues for the long cDNA reads since they would effectively contain multiple genes thus mapping to multiple genome annotations. I feel like isoform discovery could take all this into account. Or maybe I am way off. Your thoughts on this would be appreciated.

**Comment by andredsim** [comment]
Hi,

There are quite a lot of issues to unpack with prokaryotes and it is not something bambu is optimized for. Namely this occurs because of the messy start and ends of long reads making it hard to separate single-exons transcripts from each other, and this is compounded in prokarytotes which have very compact genomes with overlapping genes. 

Despite this, if you wanted to try use operon ids instead, I would recommend manually placing the operon id into the gene id field in the input gtf. While I havn't tested this, I believe this should work fine for quantification however transcript discovery will be problematic. You would need to turn on single-exon discovery but I am not sure it would provide any meaningful results. 

Sorry that I cannot be of more help here, it is something we want to improve in the future but will require a significant undertaking.

Kind Regards,
Andre Sim

**Comment by kneubehl** [comment]
I figured it was a long shot but I thought I'd reach out and see. Thank you for your insights!




Regards,


Alex Kneubehl, PhD

Postdoctoral Associate
Translational Virology Lab
Vector Biology and Bacterial Pathogens Lab
Division of Tropical Medicine

Department of Pediatrics

Baylor College of Medicine

Twitter: @AlexKneubehl




________________________________
