### ISSUE TITLE
Differences between uniqueCounts_transcript.txt and readToTranscriptMaps

### ISSUE THREAD

**Issue by camelest** [GoekeLab/bambu#437]
Hi, thank you so much for a great tool!

I'm trying to use `Bambu` to perform count from single-cell long-read data. My input bam file is already deduplicated and I want to break down the count result by the readID from bam.

When I check the total count from the 2nd column in `uniqueCounts_transript.txt` and the number of molecules with non-NULL values in `equalMatches` or `compatibleMatches` from `metadata(se.quantOnly)$readToTranscriptMaps[[1]]`, I have by far less number in the latter.

```
se.quantOnly <- bambu(reads = "input.bam", 
                      annotations = "annotations", 
                      genome = "reference.fa",
                      discovery = FALSE, 
                      trackReads = TRUE)

df <- metadata(se.quantOnly)$readToTranscriptMaps[[1]]
df_filtered <- df[!sapply(df$equalMatches, is.null), ]
df_filtered <- df_filtered[!sapply(df_filtered$compatibleMatches, is.null), ]

dim(df)
[1] 77543914        3
dim(df_filtered)
[1] 1906345       3

awk '{ sum += $3 } END { print sum }' uniqueCounts_transcript.txt 
40450053
```

I would really appreciate it if you have any comments on the discrepancy. 
Thank you so much.

**Comment by andredsim** [comment]
Hi,

Thanks for you using Bambu. Keep in mind that the current version of Bambu is not designed with single-cell in mind, and a different single-cell version of Bambu is currently in beta at the moment. 

I believe instead of looking at the uniqueCounts output which represents the reads that can be uniquely assigned to only one transcript (unrelated to equalMatches of compatibleMatches), you want to look at the fullLengthCounts which is related to equalMatches. The majority of reads will also not be equal matches (FSM in squanti terminology) so filtering by NULL in equal matches will always remove a lot of counts. There will still be a discrepancy between the number of fullLengthCounts and equalMatches however, as there are usually multiple transcripts in the annotations with the same splice forms, which bambu considers equal matches. 

I do want to caution using the readToTranscriptMap to generate quantification results, as unlike some other long-read methods Bambu does not quantify using direct read to transcript assignments and uses an expectation maximization strategy instead, which this method would not capture. Of course you are welcome to try this, but I would only recommend it if you were wanting to know how many reads fully supported your transcript of interest, rather than accurate quantification estimates.

If you have further questions, feel free to ask. 

Kind Regards,
Andre Sim

**Comment by camelest** [comment]
Dear Andre,

Thank you so much for the detailed explanation. I see, now I understood that the discrepancy is as expected.

I also checked your beta release of single-cell-version bambu and I get stuck here.
Anyway, I will wait for your official release! Thank you for your kind help.

```  --- Start isoform quantification ---
  Error in reducer$value.cache[[as.character(idx)]] <- values : 
    wrong args for environment subassignment
  Calls: bambu ... .bploop_impl -> .collect_result -> .reducer_add -> .reducer_add
  In addition: Warning message:
  In parallel::mccollect(wait = FALSE, timeout = 1) :
    1 parallel job did not deliver a result
  Execution halted
  Error while shutting down parallel: unable to terminate some child processes
  INFO:    Cleaning up image...
```

Best,
Raku

**Comment by andredsim** [comment]
Would you please be able to post that error (the full output if possible) and the command line you used to call it on the single cell issues page, and we will try solve the issue there. There are a few issues when trying to run the pipeline on other platforms which we are still trying to resolve. I will close this one here for now, but feel free to open it again if you have other related issues.

Thanks!

**Comment by camelest** [comment]
Sure, thank you so much for your help!
